export const TOPICS = [
  { id: 'delay', title: 'Delay & Networking Basics' },
  { id: 'throughput', title: 'Data & Throughput' },
  { id: 'switching', title: 'Packet Switching' },
  { id: 'capacity', title: 'Bandwidth & Capacity' },
  { id: 'signal', title: 'Signal & Noise' },
  { id: 'protocol', title: 'Protocols & Flow Control' },
  { id: 'misc', title: 'Misc' },
]

export const PROBLEMS = [
  // ── DELAY ─────────────────────────────────────────────────────────────────
  {
    id: 'transmission_delay',
    topic: 'delay',
    title: 'Transmission Delay (Td)',
    description: 'Time to push L bits onto a link of rate R.',
    inputs: [
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'Td = L / R' },
    difficulty: 'easy',
    tips: ['Increasing the link rate R directly reduces transmission delay.', 'Transmission delay depends on packet size, not distance.'],
    relatedIds: ['propagation_delay', 'total_delay', 'store_forward_delay'],
    interpretation: 'Transmission delay is the time taken to serialize all bits of the packet onto the link.',
  },
  {
    id: 'propagation_delay',
    topic: 'delay',
    title: 'Propagation Delay (Tp)',
    description: 'Time for signal to travel distance d at speed s.',
    inputs: [
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'Tp = d / s' },
    difficulty: 'easy',
    tips: ['Propagation delay depends only on distance and medium, not on packet size.', 'In fiber optics, s ≈ 2×10⁸ m/s.'],
    relatedIds: ['transmission_delay', 'total_delay', 'rtt_calculation'],
    interpretation: 'Propagation delay is the time for the first bit to travel from sender to receiver.',
  },
  {
    id: 'total_delay',
    topic: 'delay',
    title: 'Total Delay (Transmission + Propagation)',
    description: 'Adds transmission and propagation delay for a single link.',
    inputs: [
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'T = (L/R) + (d/s)' },
    difficulty: 'easy',
    tips: ['For short fast links, propagation dominates; for slow links, transmission dominates.', 'This is the minimum one-way delay for a single link.'],
    relatedIds: ['transmission_delay', 'propagation_delay', 'end_to_end_delay'],
    interpretation: 'Total single-link delay combines the time to transmit all bits and the time for them to propagate.',
  },
  {
    id: 'end_to_end_delay',
    topic: 'delay',
    title: 'End-to-End Delay (Multi-Hop)',
    description: 'Total delay across N store-and-forward hops with propagation.',
    inputs: [
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Total distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '300', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
      { key: 'N', label: 'Number of hops (N)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '3', min: 1 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'T = N×(L/R) + (d/s)' },
    difficulty: 'medium',
    tips: ['Each hop adds a full transmission delay; total propagation covers the full path.', 'Store-and-forward: each router must fully receive the packet before forwarding.'],
    relatedIds: ['total_delay', 'store_forward_delay', 'pipelining_delay'],
    interpretation: 'End-to-end delay accounts for N store-and-forward transmissions plus the total propagation across the path.',
  },
  {
    id: 'store_forward_delay',
    topic: 'delay',
    title: 'Store-and-Forward Delay',
    description: 'Delay when a packet is fully received at each of N links before forwarding.',
    inputs: [
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'N', label: 'Number of links (N)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '3', min: 1 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'T = N × (L/R)' },
    difficulty: 'medium',
    tips: ['With N links, total transmission time is N times the single-link delay.', 'Pipelining can reduce this to (N+P−1)×(L/R) for P packets.'],
    relatedIds: ['transmission_delay', 'end_to_end_delay', 'pipelining_delay'],
    interpretation: 'Store-and-forward adds one full transmission delay per link traversed.',
  },

  // ── THROUGHPUT ─────────────────────────────────────────────────────────────
  {
    id: 'effective_throughput_with_loss',
    topic: 'throughput',
    title: 'Effective Throughput (with loss)',
    description: 'Throughput adjusted by (1 - lossRate).',
    inputs: [
      { key: 'R', label: 'Link throughput (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'loss', label: 'Loss rate', quantity: 'ratio', required: true, defaultUnit: 'percent', defaultValue: '1', min: 0, max: 100 },
    ],
    result: { quantity: 'dataRate', unit: 'Mbps' },
    formula: { quick: 'Reff = R × (1 - loss)' },
    difficulty: 'easy',
    tips: ['Even 1% loss can significantly reduce effective throughput.', 'Loss rate includes both corruption and congestion drops.'],
    relatedIds: ['goodput', 'max_throughput_constraints', 'packet_loss_impact'],
    interpretation: 'Effective throughput reflects the usable data rate after accounting for packet loss.',
  },
  {
    id: 'goodput',
    topic: 'throughput',
    title: 'Goodput',
    description: 'Application payload rate excluding headers.',
    inputs: [
      { key: 'R', label: 'Throughput (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'payload', label: 'Payload fraction', quantity: 'ratio', required: true, defaultUnit: 'percent', defaultValue: '90', min: 0, max: 100 },
    ],
    result: { quantity: 'dataRate', unit: 'Mbps' },
    formula: { quick: 'Goodput = R × payload%' },
    difficulty: 'easy',
    tips: ['Goodput is always ≤ throughput due to headers and retransmissions.', 'Large payloads improve goodput by reducing header overhead fraction.'],
    relatedIds: ['effective_throughput_with_loss', 'link_utilization', 'fragmentation'],
    interpretation: 'Goodput is the rate of useful application data delivered, excluding protocol overhead.',
  },
  {
    id: 'link_utilization',
    topic: 'throughput',
    title: 'Link Utilization',
    description: 'Fraction of link capacity consumed by arriving traffic.',
    inputs: [
      { key: 'arrival_rate', label: 'Arrival rate', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '7', min: 0 },
      { key: 'link_capacity', label: 'Link capacity', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
    ],
    result: { quantity: 'ratio', unit: 'percent' },
    formula: { quick: 'U = arrival_rate / link_capacity × 100%' },
    difficulty: 'easy',
    tips: ['Utilization above ~80% often leads to significant queuing delay.', 'Keep utilization below 70–75% for stable, low-latency performance.'],
    relatedIds: ['traffic_intensity', 'goodput', 'bandwidth_delay_product'],
    interpretation: 'Link utilization shows what fraction of available bandwidth is being consumed.',
  },
  {
    id: 'bandwidth_delay_product',
    topic: 'throughput',
    title: 'Bandwidth-Delay Product (BDP)',
    description: 'Volume of data "in flight" on the link at any time.',
    inputs: [
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'RTT', label: 'Round-trip time (RTT)', quantity: 'time', required: true, defaultUnit: 'ms', defaultValue: '50', min: 0 },
    ],
    result: { quantity: 'dataSize', unit: 'bit' },
    formula: { quick: 'BDP = R × RTT' },
    difficulty: 'medium',
    tips: ['BDP determines the required window size for full link utilization.', 'A large BDP means the protocol needs large buffers to be efficient.'],
    relatedIds: ['sliding_window_throughput', 'stop_wait_efficiency', 'rtt_calculation'],
    interpretation: 'The BDP is the maximum amount of unacknowledged data that can be in transit to fully utilize the link.',
  },
  {
    id: 'max_throughput_constraints',
    topic: 'throughput',
    title: 'Maximum Throughput under Constraints',
    description: 'Effective throughput considering window size, RTT, and loss rate.',
    inputs: [
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'W', label: 'Window size (W, packets)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '4', min: 1 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
      { key: 'loss', label: 'Loss rate', quantity: 'ratio', required: true, defaultUnit: 'percent', defaultValue: '1', min: 0, max: 100 },
    ],
    result: { quantity: 'dataRate', unit: 'Mbps' },
    formula: { quick: 'If W×Td≥RTT: Tmax=R×(1−loss); else Tmax=W×R/(1+2a)×(1−loss)' },
    difficulty: 'exam',
    tips: ['If window size fills the pipe, throughput is limited only by loss rate.', 'Increase W until W×Td ≥ 2×Tp for full utilization.'],
    relatedIds: ['sliding_window_throughput', 'bandwidth_delay_product', 'effective_throughput_with_loss'],
    interpretation: 'Maximum throughput balances the window-size constraint and packet loss over the link.',
  },

  // ── SWITCHING ──────────────────────────────────────────────────────────────
  {
    id: 'num_packets_required',
    topic: 'switching',
    title: 'Number of Packets Required',
    description: 'Packets needed to carry a message M given packet size L and header H.',
    inputs: [
      { key: 'M', label: 'Message size (M)', quantity: 'dataSize', required: true, defaultUnit: 'KB', defaultValue: '10', min: 0 },
      { key: 'L', label: 'Packet/frame size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'H', label: 'Header size per packet (H)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '40', min: 0 },
    ],
    result: { quantity: 'count', unit: 'count' },
    formula: { quick: 'N = ⌈M / (L − H)⌉' },
    difficulty: 'easy',
    tips: ['Headers reduce payload per packet; smaller packets mean proportionally more overhead.', 'Always round up — you cannot send a fractional packet.'],
    relatedIds: ['time_send_message', 'fragmentation', 'pipelining_delay'],
    interpretation: 'The number of packets determines total overhead and affects delivery time.',
  },
  {
    id: 'time_send_message',
    topic: 'switching',
    title: 'Time to Send Entire Message',
    description: 'Total time to transmit a full message across one link including propagation.',
    inputs: [
      { key: 'M', label: 'Message size (M)', quantity: 'dataSize', required: true, defaultUnit: 'KB', defaultValue: '10', min: 0 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'T = ⌈M/L⌉ × (L/R) + (d/s)' },
    difficulty: 'medium',
    tips: ['The last packet arrives one propagation-delay after the last bit is sent.', 'For a single link, total time ≈ M/R + d/s when M >> L.'],
    relatedIds: ['num_packets_required', 'pipelining_delay', 'circuit_vs_packet'],
    interpretation: 'Time to send a full message includes all packet transmissions plus one propagation delay.',
  },
  {
    id: 'circuit_vs_packet',
    topic: 'switching',
    title: 'Circuit vs Packet Switching',
    description: 'Compare total transfer time for circuit switching vs packet switching.',
    inputs: [
      { key: 'M', label: 'Message size (M)', quantity: 'dataSize', required: true, defaultUnit: 'KB', defaultValue: '100', min: 0 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Distance per link (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
      { key: 'setup_time', label: 'Circuit setup time', quantity: 'time', required: true, defaultUnit: 'ms', defaultValue: '500', min: 0 },
      { key: 'N_links', label: 'Number of links (N)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '3', min: 1 },
    ],
    result: { quantity: 'time', unit: 's' },
    formula: { quick: 'Circuit: T_c = setup+M/R+N×(d/s); Packet: T_p = ⌈M/L⌉×(L/R)+N×(d/s)' },
    difficulty: 'medium',
    tips: ['Circuit switching is better for continuous long transfers; packet switching for short bursty traffic.', 'Circuit setup time is amortized over long connections.'],
    relatedIds: ['time_send_message', 'pipelining_delay', 'store_forward_delay'],
    interpretation: 'Packet switching avoids setup overhead; circuit switching offers guaranteed bandwidth.',
  },
  {
    id: 'pipelining_delay',
    topic: 'switching',
    title: 'Delay with Pipelining',
    description: 'Total delay when packets are pipelined across N hops.',
    inputs: [
      { key: 'M', label: 'Message size (M)', quantity: 'dataSize', required: true, defaultUnit: 'KB', defaultValue: '10', min: 0 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Distance per hop (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
      { key: 'N_hops', label: 'Number of hops (N)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '3', min: 1 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'T = (N_hops + N_pkts − 1)×(L/R) + N_hops×(d/s)' },
    difficulty: 'exam',
    tips: ['Pipelining significantly reduces total transfer time for multi-hop paths.', 'The (N_pkts−1) term accounts for packets still in flight while the last one is being sent.'],
    relatedIds: ['store_forward_delay', 'end_to_end_delay', 'time_send_message'],
    interpretation: 'Pipelining overlaps transmissions across hops, reducing total delay compared to sequential forwarding.',
  },
  {
    id: 'fragmentation',
    topic: 'switching',
    title: 'Fragmentation Calculation',
    description: 'Fragments produced and overhead when a datagram is fragmented.',
    inputs: [
      { key: 'M', label: 'Original datagram size (M)', quantity: 'dataSize', required: true, defaultUnit: 'KB', defaultValue: '4', min: 0 },
      { key: 'L', label: 'Fragment size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'H', label: 'Header per fragment (H)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '20', min: 0 },
    ],
    result: { quantity: 'count', unit: 'count' },
    formula: { quick: 'N = ⌈M/L⌉,  overhead = N×H' },
    difficulty: 'medium',
    tips: ['Each fragment carries its own header, adding overhead.', 'IP fragmentation happens at the network layer; TCP avoids it via MSS negotiation.'],
    relatedIds: ['num_packets_required', 'goodput', 'time_send_message'],
    interpretation: 'Fragmentation result shows the number of fragments created from the original datagram.',
  },

  // ── CAPACITY ───────────────────────────────────────────────────────────────
  {
    id: 'shannon_capacity',
    topic: 'capacity',
    title: 'Shannon Capacity',
    description: 'C = B log₂(1 + SNR).',
    inputs: [
      { key: 'B', label: 'Bandwidth (B)', quantity: 'frequency', required: true, defaultUnit: 'MHz', defaultValue: '1', min: 0 },
      { key: 'snr', label: 'SNR (linear)', quantity: 'ratio', required: true, defaultUnit: 'linear', defaultValue: '10', min: 0 },
    ],
    result: { quantity: 'dataRate', unit: 'Mbps' },
    formula: { quick: 'C = B log₂(1+SNR)' },
    difficulty: 'medium',
    tips: ['Doubling SNR adds only log₂(2) = 1 bit/s/Hz of capacity.', 'Shannon capacity is a theoretical upper bound; practical systems achieve less.'],
    relatedIds: ['traffic_intensity', 'link_utilization', 'bandwidth_delay_product'],
    interpretation: 'Shannon capacity is the theoretical maximum data rate achievable over a noisy channel.',
  },
  {
    id: 'traffic_intensity',
    topic: 'capacity',
    title: 'Traffic Intensity',
    description: 'Fraction of link capacity used, ρ = λL/R.',
    inputs: [
      { key: 'lambda', label: 'Arrival rate λ (packets/s)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '100', min: 0 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link capacity (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
    ],
    result: { quantity: 'ratio', unit: 'linear' },
    formula: { quick: 'ρ = λL / R' },
    difficulty: 'medium',
    tips: ['ρ must be < 1 for a stable queue; ρ ≥ 1 means infinite queuing.', 'At ρ = 0.9, queuing delay grows very rapidly — keep ρ well below 1.'],
    relatedIds: ['queuing_delay_mm1', 'link_utilization', 'buffer_overflow'],
    interpretation: 'Traffic intensity ρ = 1 means the link is fully loaded; > 1 means packets arrive faster than they can be served.',
  },
  {
    id: 'buffer_overflow',
    topic: 'capacity',
    title: 'Buffer Overflow Time',
    description: 'Time until buffer overflows when arrival rate exceeds service rate.',
    inputs: [
      { key: 'buffer_size', label: 'Buffer size', quantity: 'dataSize', required: true, defaultUnit: 'KB', defaultValue: '64', min: 0 },
      { key: 'arrival_rate', label: 'Arrival rate', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '12', min: 0 },
      { key: 'service_rate', label: 'Service rate', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
    ],
    result: { quantity: 'time', unit: 's' },
    formula: { quick: 'T = buffer / (arrival − service)  [if arrival > service]' },
    difficulty: 'exam',
    tips: ['Overflow only occurs when arrival rate > service rate; otherwise the buffer drains.', 'Larger buffers delay overflow but do not prevent it if overload persists.'],
    relatedIds: ['traffic_intensity', 'queuing_delay_mm1', 'link_utilization'],
    interpretation: 'Buffer overflow time shows how long the network can absorb a traffic burst before dropping packets.',
  },

  // ── PROTOCOL ───────────────────────────────────────────────────────────────
  {
    id: 'stop_wait_efficiency',
    topic: 'protocol',
    title: 'Stop-and-Wait Protocol Efficiency',
    description: 'Fraction of time the sender is actually transmitting data.',
    inputs: [
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
    ],
    result: { quantity: 'ratio', unit: 'percent' },
    formula: { quick: 'η = Td / (Td + 2×Tp)' },
    difficulty: 'medium',
    tips: ['Stop-and-Wait is very inefficient on high-bandwidth long-delay links.', 'Pipelining (sliding window) overcomes this inefficiency.'],
    relatedIds: ['sliding_window_throughput', 'bandwidth_delay_product', 'rtt_calculation'],
    interpretation: 'Stop-and-wait efficiency shows what fraction of time is spent sending useful data.',
  },
  {
    id: 'sliding_window_throughput',
    topic: 'protocol',
    title: 'Sliding Window Throughput Efficiency',
    description: 'Effective throughput efficiency with a send window of W packets.',
    inputs: [
      { key: 'W', label: 'Window size (W, packets)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '4', min: 1 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
    ],
    result: { quantity: 'ratio', unit: 'percent' },
    formula: { quick: 'η = min(W, 1+2a) / (1+2a),  a = Tp/Td' },
    difficulty: 'exam',
    tips: ['Set W ≥ 1 + 2a to achieve 100% efficiency.', 'a = Tp/Td is the normalised propagation-to-transmission delay ratio.'],
    relatedIds: ['stop_wait_efficiency', 'bandwidth_delay_product', 'max_throughput_constraints'],
    interpretation: 'Sliding window efficiency shows how much of the available bandwidth is being utilized.',
  },
  {
    id: 'rtt_calculation',
    topic: 'protocol',
    title: 'RTT Calculation',
    description: 'Round-trip time including propagation and processing delay.',
    inputs: [
      { key: 'd', label: 'Distance (d)', quantity: 'distance', required: true, defaultUnit: 'km', defaultValue: '100', min: 0 },
      { key: 's', label: 'Propagation speed (s)', quantity: 'speed', required: true, defaultUnit: 'm/s', defaultValue: '200000000', min: 0 },
      { key: 'proc_delay', label: 'Processing delay', quantity: 'time', required: true, defaultUnit: 'ms', defaultValue: '1', min: 0 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'RTT = 2×(d/s) + proc_delay' },
    difficulty: 'easy',
    tips: ['RTT is round-trip, so propagation is counted twice.', 'Processing delay at routers adds to RTT in practice.'],
    relatedIds: ['propagation_delay', 'bandwidth_delay_product', 'stop_wait_efficiency'],
    interpretation: 'RTT determines the minimum time between sending a packet and receiving its acknowledgement.',
  },

  // ── MISC ───────────────────────────────────────────────────────────────────
  {
    id: 'queuing_delay_mm1',
    topic: 'misc',
    title: 'Queuing Delay (M/M/1)',
    description: 'Average waiting time in queue for an M/M/1 system.',
    inputs: [
      { key: 'lambda', label: 'Arrival rate λ (packets/s)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '80', min: 0 },
      { key: 'mu', label: 'Service rate μ (packets/s)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '100', min: 0 },
    ],
    result: { quantity: 'time', unit: 's' },
    formula: { quick: 'Wq = λ / (μ×(μ−λ))' },
    difficulty: 'exam',
    tips: ['Queuing delay grows rapidly as ρ = λ/μ approaches 1.', 'Wq diverges to ∞ as ρ → 1; the system is unstable for ρ ≥ 1.'],
    relatedIds: ['traffic_intensity', 'buffer_overflow', 'link_utilization'],
    interpretation: 'M/M/1 queuing delay is the average time a packet waits in the queue before being served.',
  },
  {
    id: 'packet_loss_impact',
    topic: 'misc',
    title: 'Packet Loss Impact',
    description: 'Number of packets lost and received given a total count and loss rate.',
    inputs: [
      { key: 'N_total', label: 'Total packets sent', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '1000', min: 0 },
      { key: 'loss_rate', label: 'Loss rate', quantity: 'ratio', required: true, defaultUnit: 'percent', defaultValue: '5', min: 0, max: 100 },
    ],
    result: { quantity: 'count', unit: 'count' },
    formula: { quick: 'N_recv = N_total × (1 − loss_rate)' },
    difficulty: 'easy',
    tips: ['A 5% loss rate means roughly 1 in 20 packets is dropped.', 'TCP retransmits lost packets, increasing actual transmission time.'],
    relatedIds: ['effective_throughput_with_loss', 'max_throughput_constraints', 'reassembly_time'],
    interpretation: 'Packet loss impact shows how many packets are successfully delivered to the destination.',
  },
  {
    id: 'reassembly_time',
    topic: 'misc',
    title: 'Reassembly Time',
    description: 'Time to receive all N packets of a message at the destination.',
    inputs: [
      { key: 'N', label: 'Number of packets (N)', quantity: 'count', required: true, defaultUnit: 'count', defaultValue: '10', min: 1 },
      { key: 'L', label: 'Packet size (L)', quantity: 'dataSize', required: true, defaultUnit: 'byte', defaultValue: '1500', min: 0 },
      { key: 'R', label: 'Link rate (R)', quantity: 'dataRate', required: true, defaultUnit: 'Mbps', defaultValue: '10', min: 0 },
    ],
    result: { quantity: 'time', unit: 'ms' },
    formula: { quick: 'T = N × (L/R)' },
    difficulty: 'medium',
    tips: ['Reassembly time assumes back-to-back transmission with no gaps.', 'In practice, add queuing and propagation delays for a realistic estimate.'],
    relatedIds: ['fragmentation', 'num_packets_required', 'time_send_message'],
    interpretation: 'Reassembly time is the minimum time for the last bit of the final packet to arrive.',
  },
]

export function problemsByTopic() {
  const map = new Map()
  for (const t of TOPICS) map.set(t.id, [])
  for (const p of PROBLEMS) {
    if (!map.has(p.topic)) map.set(p.topic, [])
    map.get(p.topic).push(p)
  }
  return map
}
